// Code generated by hertz generator.

// @title           eigenflux_server Console API
// @version         1.0
// @description     EigenFlux Console API for querying and managing agents and items
// @host            localhost:8090
// @BasePath        /

package main

import (
	"log"
	"os"
	"strings"

	"eigenflux_server/console/api/dal"
	_ "eigenflux_server/console/api/docs"
	"eigenflux_server/pkg/config"
	"eigenflux_server/pkg/db"
	"eigenflux_server/pkg/logger"
	"eigenflux_server/pkg/mq"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	hertzSwagger "github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

func main() {
	cfg := config.Load()
	logger.Init("console/api/.log")

	// Init PostgreSQL
	db.Init(cfg.PgDSN)
	log.Println("PostgreSQL connected")

	// Init Redis (for both console DAL and mq package)
	if err := dal.InitRedis(cfg.RedisAddr, cfg.RedisPassword); err != nil {
		log.Fatalf("failed to connect redis: %v", err)
	}
	mq.Init(cfg.RedisAddr, cfg.RedisPassword)
	log.Println("Redis connected")

	listenAddr := cfg.ListenAddr(cfg.ConsoleApiPort)
	h := server.Default(server.WithHostPorts(listenAddr))

	allowOrigins := parseAllowOrigins()
	h.Use(cors.New(cors.Config{
		AllowOrigins:     allowOrigins,
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept"},
		AllowCredentials: false,
	}))

	// Swagger UI
	h.GET("/swagger/*any", hertzSwagger.WrapHandler(swaggerFiles.Handler))

	register(h)

	log.Printf("Console API gateway starting on %s", listenAddr)
	h.Spin()
}

func parseAllowOrigins() []string {
	raw := strings.TrimSpace(os.Getenv("CONSOLE_CORS_ALLOW_ORIGINS"))
	if raw == "" {
		return []string{"*"}
	}
	parts := strings.Split(raw, ",")
	origins := make([]string, 0, len(parts))
	for _, part := range parts {
		origin := strings.TrimSpace(part)
		if origin != "" {
			origins = append(origins, origin)
		}
	}
	if len(origins) == 0 {
		return []string{"*"}
	}
	return origins
}
